// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService handles AI chat and analysis features.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../internal/ai/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} message
 * @returns {$CancellablePromise<$models.ChatResponse | null>}
 */
export function ChatWithAI(message) {
    return $Call.ByID(1082724026, message).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearChatHistory() {
    return $Call.ByID(3032116087);
}

/**
 * ClearProjectChatHistory clears in-memory and DB chat history for a specific project.
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function ClearProjectChatHistory(projectID) {
    return $Call.ByID(4245966670, projectID);
}

/**
 * @param {string} taskId
 * @returns {$CancellablePromise<string>}
 */
export function DecomposeTask(taskId) {
    return $Call.ByID(2936384602, taskId);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GenerateWeeklyReport() {
    return $Call.ByID(3661357588);
}

/**
 * GetAIClient returns the underlying Claude client.
 * @returns {$CancellablePromise<ai$0.ClaudeClient | null>}
 */
export function GetAIClient() {
    return $Call.ByID(881979379).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetChatHistory retrieves persisted chat messages for a project.
 * @param {string} projectID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetChatHistory(projectID, limit, offset) {
    return $Call.ByID(1131401312, projectID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDailySummary() {
    return $Call.ByID(968499405);
}

/**
 * GetProactiveSuggestions returns AI-generated suggestions for the given project.
 * @param {string} projectID
 * @returns {$CancellablePromise<string>}
 */
export function GetProactiveSuggestions(projectID) {
    return $Call.ByID(2685169996, projectID);
}

/**
 * @param {string} projectId
 * @returns {$CancellablePromise<string>}
 */
export function PrioritizeTasks(projectId) {
    return $Call.ByID(2536206107, projectId);
}

/**
 * ReloadClient re-initialises the AI client from stored config.
 * @returns {$CancellablePromise<void>}
 */
export function ReloadClient() {
    return $Call.ByID(2290836672);
}

/**
 * @param {string} projectId
 * @returns {$CancellablePromise<string>}
 */
export function SmartSuggestTasks(projectId) {
    return $Call.ByID(1202614731, projectId);
}

/**
 * StreamChatWithAI starts a streaming chat session and emits Wails events for each chunk.
 * @param {string} message
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function StreamChatWithAI(message, projectID) {
    return $Call.ByID(2213761922, message, projectID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function TestAIConnection() {
    return $Call.ByID(2655471488);
}

// Private type creation functions
const $$createType0 = $models.ChatResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ai$0.ClaudeClient.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType4);
