// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService handles AI chat and analysis features.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../internal/ai/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChatWithAI(message: string): $CancellablePromise<$models.ChatResponse | null> {
    return $Call.ByID(1082724026, message).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ClearChatHistory(): $CancellablePromise<void> {
    return $Call.ByID(3032116087);
}

/**
 * ClearProjectChatHistory clears in-memory and DB chat history for a specific project.
 */
export function ClearProjectChatHistory(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(4245966670, projectID);
}

export function DecomposeTask(taskId: string): $CancellablePromise<string> {
    return $Call.ByID(2936384602, taskId);
}

export function GenerateWeeklyReport(): $CancellablePromise<string> {
    return $Call.ByID(3661357588);
}

/**
 * GetAIClient returns the underlying Claude client.
 */
export function GetAIClient(): $CancellablePromise<ai$0.ClaudeClient | null> {
    return $Call.ByID(881979379).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetChatHistory retrieves persisted chat messages for a project.
 */
export function GetChatHistory(projectID: string, limit: number, offset: number): $CancellablePromise<{ [_: string]: any }[]> {
    return $Call.ByID(1131401312, projectID, limit, offset).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetDailySummary(): $CancellablePromise<string> {
    return $Call.ByID(968499405);
}

/**
 * GetProactiveSuggestions returns AI-generated suggestions for the given project.
 */
export function GetProactiveSuggestions(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(2685169996, projectID);
}

export function PrioritizeTasks(projectId: string): $CancellablePromise<string> {
    return $Call.ByID(2536206107, projectId);
}

/**
 * ReloadClient re-initialises the AI client from stored config.
 */
export function ReloadClient(): $CancellablePromise<void> {
    return $Call.ByID(2290836672);
}

export function SmartSuggestTasks(projectId: string): $CancellablePromise<string> {
    return $Call.ByID(1202614731, projectId);
}

/**
 * StreamChatWithAI starts a streaming chat session and emits Wails events for each chunk.
 */
export function StreamChatWithAI(message: string, projectID: string): $CancellablePromise<void> {
    return $Call.ByID(2213761922, message, projectID);
}

export function TestAIConnection(): $CancellablePromise<void> {
    return $Call.ByID(2655471488);
}

// Private type creation functions
const $$createType0 = $models.ChatResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ai$0.ClaudeClient.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType4);
