// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService handles application configuration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AIConfig | null>}
 */
export function GetAIConfig() {
    return $Call.ByID(1514248118).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAPIKey() {
    return $Call.ByID(3594034821);
}

/**
 * GetConfig returns a raw config value by key.
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetConfig(key) {
    return $Call.ByID(3463536948, key);
}

/**
 * @param {string} apiKey
 * @param {string} baseURL
 * @param {string} modelName
 * @returns {$CancellablePromise<void>}
 */
export function SaveAIConfig(apiKey, baseURL, modelName) {
    return $Call.ByID(199356151, apiKey, baseURL, modelName);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SaveAPIKey(key) {
    return $Call.ByID(4111962512, key);
}

/**
 * SetConfig sets a raw config value by key.
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetConfig(key, value) {
    return $Call.ByID(2251701264, key, value);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function TestAIConnection() {
    return $Call.ByID(931474788);
}

// Private type creation functions
const $$createType0 = $models.AIConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
