// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeishuService 飞书集成服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoStart 根据配置自动启动同步
 */
export function AutoStart(): $CancellablePromise<void> {
    return $Call.ByID(3079232907);
}

/**
 * GetBotConfig 获取 Bot 配置
 */
export function GetBotConfig(): $CancellablePromise<$models.BotConfig | null> {
    return $Call.ByID(2660033769).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFeishuConfig 获取飞书配置
 */
export function GetFeishuConfig(): $CancellablePromise<$models.FeishuConfig | null> {
    return $Call.ByID(2148313998).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSyncStatus 获取同步状态
 */
export function GetSyncStatus(): $CancellablePromise<$models.SyncStatus> {
    return $Call.ByID(430838123).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * HandleBotMessage 处理 Bot 收到的消息（路由到 AI）
 */
export function HandleBotMessage(chatID: string, userMessage: string): $CancellablePromise<void> {
    return $Call.ByID(3836364988, chatID, userMessage);
}

/**
 * NotifyTaskChanged 任务变更通知（发送卡片到配置的群）
 */
export function NotifyTaskChanged(taskTitle: string, status: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(3194633814, taskTitle, status, action);
}

/**
 * SaveBotConfig 保存 Bot 配置
 */
export function SaveBotConfig(cfg: $models.BotConfig): $CancellablePromise<void> {
    return $Call.ByID(229379230, cfg);
}

/**
 * SaveFeishuConfig 保存飞书配置并重新初始化客户端
 */
export function SaveFeishuConfig(cfg: $models.FeishuConfig): $CancellablePromise<void> {
    return $Call.ByID(462487747, cfg);
}

/**
 * SendBotMessage 通过 Bot 发送消息到配置的群
 */
export function SendBotMessage(text: string): $CancellablePromise<void> {
    return $Call.ByID(1703266088, text);
}

/**
 * StartSync 启动后台定时同步
 */
export function StartSync(): $CancellablePromise<void> {
    return $Call.ByID(4189766421);
}

/**
 * StopSync 停止同步
 */
export function StopSync(): $CancellablePromise<void> {
    return $Call.ByID(114618845);
}

/**
 * SyncNow 立即执行一次同步
 */
export function SyncNow(): $CancellablePromise<void> {
    return $Call.ByID(2717776935);
}

/**
 * TestConnection 测试飞书连接
 */
export function TestConnection(): $CancellablePromise<void> {
    return $Call.ByID(2958501946);
}

// Private type creation functions
const $$createType0 = $models.BotConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FeishuConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.SyncStatus.createFrom;
