// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService exposes log file operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearOldLogs removes log files older than the given number of days.
 * Returns the number of files removed.
 */
export function ClearOldLogs(days: number): $CancellablePromise<number> {
    return $Call.ByID(877336849, days);
}

/**
 * ExportLogs opens a native save dialog and copies the specified log file.
 */
export function ExportLogs(filename: string): $CancellablePromise<void> {
    return $Call.ByID(3535749673, filename);
}

/**
 * GetLogContent reads the last tailLines lines from a log file.
 */
export function GetLogContent(filename: string, tailLines: number): $CancellablePromise<string> {
    return $Call.ByID(1458902899, filename, tailLines);
}

/**
 * GetLogFiles returns all log files sorted by date descending.
 */
export function GetLogFiles(): $CancellablePromise<$models.LogFileInfo[]> {
    return $Call.ByID(46327229).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenLogDir opens the log directory in the system file manager.
 */
export function OpenLogDir(): $CancellablePromise<void> {
    return $Call.ByID(4184650229);
}

// Private type creation functions
const $$createType0 = $models.LogFileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
