// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MeetingService 会议录音服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeMeeting 对会议进行 AI 分析
 */
export function AnalyzeMeeting(meetingID: string): $CancellablePromise<ai$0.MeetingAnalysis | null> {
    return $Call.ByID(2833157566, meetingID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateMeeting(title: string, projectID: string): $CancellablePromise<model$0.Meeting | null> {
    return $Call.ByID(2503140408, title, projectID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateTasksFromMeeting 从会议建议批量创建任务
 */
export function CreateTasksFromMeeting(meetingID: string, tasks: ai$0.SuggestedTask[]): $CancellablePromise<void> {
    return $Call.ByID(690044980, meetingID, tasks);
}

/**
 * DecomposeMeetingTasks 从会议分解任务
 */
export function DecomposeMeetingTasks(meetingID: string): $CancellablePromise<ai$0.SuggestedTask[]> {
    return $Call.ByID(63533105, meetingID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function DeleteMeeting(id: string): $CancellablePromise<void> {
    return $Call.ByID(3174991469, id);
}

export function GetMeeting(id: string): $CancellablePromise<model$0.Meeting | null> {
    return $Call.ByID(1325603582, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetMeetingAnalysis 获取已有的分析结果
 */
export function GetMeetingAnalysis(meetingID: string): $CancellablePromise<ai$0.MeetingAnalysis | null> {
    return $Call.ByID(1024375996, meetingID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMeetings(): $CancellablePromise<model$0.Meeting[]> {
    return $Call.ByID(4007840759).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetMeetingsByProject(projectID: string): $CancellablePromise<model$0.Meeting[]> {
    return $Call.ByID(275925891, projectID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetRecordingState(): $CancellablePromise<$models.RecordingState> {
    return $Call.ByID(1404701933).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetSegments(meetingID: string): $CancellablePromise<model$0.TranscriptSegment[]> {
    return $Call.ByID(3497525419, meetingID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetSpeakers(meetingID: string): $CancellablePromise<model$0.MeetingSpeaker[]> {
    return $Call.ByID(960645839, meetingID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function MergeSpeakers(toID: string, fromID: string): $CancellablePromise<void> {
    return $Call.ByID(1032144571, toID, fromID);
}

export function RenameSpeaker(speakerID: string, displayName: string): $CancellablePromise<void> {
    return $Call.ByID(3821543882, speakerID, displayName);
}

export function StartRecording(title: string, projectID: string): $CancellablePromise<model$0.Meeting | null> {
    return $Call.ByID(1547050404, title, projectID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function StopRecording(): $CancellablePromise<model$0.Meeting | null> {
    return $Call.ByID(2316406442).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateMeeting(id: string, title: string, projectID: string): $CancellablePromise<void> {
    return $Call.ByID(989263843, id, title, projectID);
}

// Private type creation functions
const $$createType0 = ai$0.MeetingAnalysis.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.Meeting.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = ai$0.SuggestedTask.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType2);
const $$createType7 = $models.RecordingState.createFrom;
const $$createType8 = model$0.TranscriptSegment.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = model$0.MeetingSpeaker.createFrom;
const $$createType11 = $Create.Array($$createType10);
