// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIConfig holds the AI configuration.
 */
export class AIConfig {
    "apiKey": string;
    "baseURL": string;
    "model": string;

    /** Creates a new AIConfig instance. */
    constructor($$source: Partial<AIConfig> = {}) {
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConfig($$parsedSource as Partial<AIConfig>);
    }
}

/**
 * BotConfig 飞书 Bot 配置
 */
export class BotConfig {
    "botEnabled": boolean;
    "botChatId": string;
    "notifyOnChange": boolean;

    /** Creates a new BotConfig instance. */
    constructor($$source: Partial<BotConfig> = {}) {
        if (!("botEnabled" in $$source)) {
            this["botEnabled"] = false;
        }
        if (!("botChatId" in $$source)) {
            this["botChatId"] = "";
        }
        if (!("notifyOnChange" in $$source)) {
            this["notifyOnChange"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BotConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotConfig($$parsedSource as Partial<BotConfig>);
    }
}

/**
 * ChatResponse is returned from ChatWithAI to the frontend.
 */
export class ChatResponse {
    "text": string;
    "toolCalls": ToolCallResult[];

    /** Creates a new ChatResponse instance. */
    constructor($$source: Partial<ChatResponse> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("toolCalls" in $$source)) {
            this["toolCalls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatResponse {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolCalls" in $$parsedSource) {
            $$parsedSource["toolCalls"] = $$createField1_0($$parsedSource["toolCalls"]);
        }
        return new ChatResponse($$parsedSource as Partial<ChatResponse>);
    }
}

/**
 * FeishuConfig 飞书配置
 */
export class FeishuConfig {
    "appId": string;
    "appSecret": string;
    "bitableApp": string;
    "bitableTable": string;
    "syncEnabled": boolean;

    /**
     * 分钟
     */
    "syncInterval": number;

    /** Creates a new FeishuConfig instance. */
    constructor($$source: Partial<FeishuConfig> = {}) {
        if (!("appId" in $$source)) {
            this["appId"] = "";
        }
        if (!("appSecret" in $$source)) {
            this["appSecret"] = "";
        }
        if (!("bitableApp" in $$source)) {
            this["bitableApp"] = "";
        }
        if (!("bitableTable" in $$source)) {
            this["bitableTable"] = "";
        }
        if (!("syncEnabled" in $$source)) {
            this["syncEnabled"] = false;
        }
        if (!("syncInterval" in $$source)) {
            this["syncInterval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeishuConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FeishuConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeishuConfig($$parsedSource as Partial<FeishuConfig>);
    }
}

/**
 * LogFileInfo describes a single log file.
 */
export class LogFileInfo {
    "name": string;
    "size": number;
    "modTime": string;

    /** Creates a new LogFileInfo instance. */
    constructor($$source: Partial<LogFileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LogFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFileInfo($$parsedSource as Partial<LogFileInfo>);
    }
}

/**
 * RecordingState 录制状态
 */
export class RecordingState {
    "meetingId": string;

    /**
     * idle, recording, paused
     */
    "status": string;
    "duration": number;

    /** Creates a new RecordingState instance. */
    constructor($$source: Partial<RecordingState> = {}) {
        if (!("meetingId" in $$source)) {
            this["meetingId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingState instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordingState($$parsedSource as Partial<RecordingState>);
    }
}

/**
 * SyncStatus 同步状态
 */
export class SyncStatus {
    "running": boolean;
    "lastSyncAt": string;
    "lastError": string;
    "syncedCount": number;
    "pushedCount": number;
    "pulledCount": number;

    /** Creates a new SyncStatus instance. */
    constructor($$source: Partial<SyncStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("lastSyncAt" in $$source)) {
            this["lastSyncAt"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("syncedCount" in $$source)) {
            this["syncedCount"] = 0;
        }
        if (!("pushedCount" in $$source)) {
            this["pushedCount"] = 0;
        }
        if (!("pulledCount" in $$source)) {
            this["pulledCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncStatus($$parsedSource as Partial<SyncStatus>);
    }
}

/**
 * ToolCallResult represents the outcome of a single AI tool call.
 */
export class ToolCallResult {
    "action": string;
    "success": boolean;
    "message": string;

    /** Creates a new ToolCallResult instance. */
    constructor($$source: Partial<ToolCallResult> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCallResult($$parsedSource as Partial<ToolCallResult>);
    }
}

// Private type creation functions
const $$createType0 = ToolCallResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
