// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIConfig holds the AI configuration.
 */
export class AIConfig {
    /**
     * Creates a new AIConfig instance.
     * @param {Partial<AIConfig>} [$$source = {}] - The source object to create the AIConfig.
     */
    constructor($$source = {}) {
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("baseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConfig(/** @type {Partial<AIConfig>} */($$parsedSource));
    }
}

/**
 * ChatResponse is returned from ChatWithAI to the frontend.
 */
export class ChatResponse {
    /**
     * Creates a new ChatResponse instance.
     * @param {Partial<ChatResponse>} [$$source = {}] - The source object to create the ChatResponse.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("toolCalls" in $$source)) {
            /**
             * @member
             * @type {ToolCallResult[]}
             */
            this["toolCalls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolCalls" in $$parsedSource) {
            $$parsedSource["toolCalls"] = $$createField1_0($$parsedSource["toolCalls"]);
        }
        return new ChatResponse(/** @type {Partial<ChatResponse>} */($$parsedSource));
    }
}

/**
 * LogFileInfo describes a single log file.
 */
export class LogFileInfo {
    /**
     * Creates a new LogFileInfo instance.
     * @param {Partial<LogFileInfo>} [$$source = {}] - The source object to create the LogFileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFileInfo(/** @type {Partial<LogFileInfo>} */($$parsedSource));
    }
}

/**
 * ToolCallResult represents the outcome of a single AI tool call.
 */
export class ToolCallResult {
    /**
     * Creates a new ToolCallResult instance.
     * @param {Partial<ToolCallResult>} [$$source = {}] - The source object to create the ToolCallResult.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCallResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCallResult(/** @type {Partial<ToolCallResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ToolCallResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
