// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService handles project CRUD operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * @param {string} name
 * @param {string} description
 * @param {string} color
 * @returns {$CancellablePromise<model$0.Project | null>}
 */
export function CreateProject(name, description, color) {
    return $Call.ByID(2778051416, name, description, color).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(id) {
    return $Call.ByID(27462813, id);
}

/**
 * @returns {$CancellablePromise<model$0.Project[]>}
 */
export function GetProjects() {
    return $Call.ByID(923151623).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @param {string} name
 * @param {string} description
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProject(id, name, description, color) {
    return $Call.ByID(3507567083, id, name, description, color);
}

// Private type creation functions
const $$createType0 = model$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
