// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService handles task CRUD operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

/**
 * @param {string} title
 * @param {string} projectId
 * @param {string} description
 * @param {number} priority
 * @param {string} dueDate
 * @returns {$CancellablePromise<model$0.Task | null>}
 */
export function CreateTask(title, projectId, description, priority, dueDate) {
    return $Call.ByID(1827820032, title, projectId, description, priority, dueDate).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTask(id) {
    return $Call.ByID(3347907499, id);
}

/**
 * @returns {$CancellablePromise<model$0.Task[]>}
 */
export function GetAllTasks() {
    return $Call.ByID(3488755352).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} projectId
 * @returns {$CancellablePromise<model$0.Task[]>}
 */
export function GetTasksByProject(projectId) {
    return $Call.ByID(106418095, projectId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<model$0.Task[]>}
 */
export function GetTodayTasks() {
    return $Call.ByID(230760254).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @param {string} title
 * @param {string} projectId
 * @param {string} description
 * @param {string} status
 * @param {number} priority
 * @param {string} dueDate
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTask(id, title, projectId, description, status, priority, dueDate) {
    return $Call.ByID(320897429, id, title, projectId, description, status, priority, dueDate);
}

// Private type creation functions
const $$createType0 = model$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
