// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function ChatWithAI(arg1:string):Promise<main.ChatResponse>;

export function ClearChatHistory():Promise<void>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<model.Project>;

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<model.Task>;

export function DecomposeTask(arg1:string):Promise<string>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GenerateWeeklyReport():Promise<string>;

export function GetAIConfig():Promise<main.AIConfig>;

export function GetAPIKey():Promise<string>;

export function GetAllTasks():Promise<Array<model.Task>>;

export function GetDailySummary():Promise<string>;

export function GetProjects():Promise<Array<model.Project>>;

export function GetTasksByProject(arg1:string):Promise<Array<model.Task>>;

export function GetTodayTasks():Promise<Array<model.Task>>;

export function PrioritizeTasks(arg1:string):Promise<string>;

export function SaveAIConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveAPIKey(arg1:string):Promise<void>;

export function SmartSuggestTasks(arg1:string):Promise<string>;

export function TestAIConnection():Promise<void>;

export function UpdateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string):Promise<void>;
