// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1) {
  return window['go']['main']['App']['ChatWithAI'](arg1);
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function CreateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4, arg5);
}

export function DecomposeTask(arg1) {
  return window['go']['main']['App']['DecomposeTask'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GenerateWeeklyReport() {
  return window['go']['main']['App']['GenerateWeeklyReport']();
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetDailySummary() {
  return window['go']['main']['App']['GetDailySummary']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetTasksByProject(arg1) {
  return window['go']['main']['App']['GetTasksByProject'](arg1);
}

export function GetTodayTasks() {
  return window['go']['main']['App']['GetTodayTasks']();
}

export function PrioritizeTasks(arg1) {
  return window['go']['main']['App']['PrioritizeTasks'](arg1);
}

export function SaveAIConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAIConfig'](arg1, arg2, arg3);
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function SmartSuggestTasks(arg1) {
  return window['go']['main']['App']['SmartSuggestTasks'](arg1);
}

export function TestAIConnection() {
  return window['go']['main']['App']['TestAIConnection']();
}

export function UpdateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3, arg4);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
