// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClaudeClient wraps the Claude API.
 */
export class ClaudeClient {
    /**
     * Creates a new ClaudeClient instance.
     * @param {Partial<ClaudeClient>} [$$source = {}] - The source object to create the ClaudeClient.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeClient instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeClient}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeClient(/** @type {Partial<ClaudeClient>} */($$parsedSource));
    }
}
